#!/bin/bash

# This script is used to build the project.

BUILD_DIR="target"

if [ ! -d "$BUILD_DIR" ]; then
    mkdir "$BUILD_DIR"
    cmake -S . -B "$BUILD_DIR"
fi

pushd "$BUILD_DIR"
make -j$(nproc)
popd
